version: '3'
services:
  transaction-container:
    restart: on-failure
    container_name: transaction-v2-container-new
    image: kubernetesdemo1.azurecr.io/transaction-v2-new-image
    ports:
      - 8086:8086
    environment:
      WAIT_HOSTS: mysql:3306
    networks:
      - v1_communication-net
networks:
  v1_communication-net:
    external: true
  